version: "3.3"

services:
  front:
    container_name: qtim-front
    image: node:20.10
    restart: always
    tty: true
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
      - 4173:4173
    command:  bash -c "npm install && npm run dev"
